    name: GitHub Classroom Workflow

    on: [push]

    jobs:
      build:
        name: Autograding
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
                #- uses: education/autograding@v1
                # Runs a set of commands using the runners shell
          - name: Run a multi-line script
            run: |
              pytest test_part1.py
              pytest test_part2.py
